MAX_LIFE_FORCE=1000
MAX_MANA_POWER=1000
MAX_MOVE_SPEED=1000
MAX_ATTACK=100
MAX_DEFENSE=100

TYPE_OF_HERO = ('TANK','WARRIOR','ASSASSIN','MAGE','ARCHER')
DICT_OF_HERO={
    'TANK':'坦克',
    'WARRIOR':'战士',
    'ASSASSIN':'刺客',
    'MAGE':'法师',
    'ARCHER':'射手'
}
MAX_FORGE_TIMES = 10
# 定义士兵当前状态
STATUS_OF_SOLDIER = ('STRONG','ALLEYS','DEAD')
